### ISSUE TITLE
Plugin (LIST)

### ISSUE THREAD

**Issue by Hasan-Shaker** [xperseguers/staffdirectory#3]
- [x] - Ajouter la possibilité de mettre un point d'entrée
- [ ] - Si aucune organisation n’est sélectionnée, lister toutes les organisations
- [x] - lister les organisations sélectionnées
- [ ] - Ajouter un bouton « lister les sous-organisations des organisations sélectionnées »

**Comment by xperseguers** [comment]
- English please!
- That's a lot of different stuff to do, this should better be (partially) distinct tickets
- Ticket's description shall better describe the context of what is asked, this is way too vague

=> I'll see what I can do anyway :)

**Comment by xperseguers** [comment]
> If no organization is selected, show all organizations

This was done in a dynamic way so that you can dynamically show an arbitrary organization in a multi-organization website, having only one page for multiple subsites or alike.

This sounds like a 180° turn from what your company asked to implement months ago. Please think twice and better describe what you actually want and comment on the probable change of behaviour.

**Comment by xperseguers** [comment]
That being said, this ticket is too vague and should be made much more clear, only dealing with a single problem at a time. Closing it in that state. Please open dedicated tickets if it makes sense and clearly describe what you'd like to have, possibly some rationale, what you tried already and why you think you cannot make it on your own in your template for instance.
